baseURL = "/"
languageCode = "en-us"
title = "EQ Labs"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id="UA-153564663-1"

  title = "EQ Labs, Inc."
  [params.homepage_meta_tags]
    meta_description = "EQ Labs provides continuous intervention targeted to minimize workplace discrimination."
    meta_og_title = "EQ Labs, Inc."
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.com"
    meta_og_image = "https://www.eqlabs.io/tn.png"
    meta_og_description = "EQ Labs is a software company based in Victoria, BC."
    meta_twitter_card = "summary"
    meta_twitter_site = "@labs_eq"
    meta_twitter_creator = "@labs_eq"

# [[menu.main]]
# 	name = "Products"
# 	url = "/products/"
#     weight = 1



[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Change"
    url = "/change/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"